=== BackupTheBerlios/openaqua-svn/trunk/odaba/unsupported/ODABAICEServer/etc/odaba/opiice/certs/sslconfig.dtd
<!ELEMENT SSLConfig (client?,server?)>  
<!ELEMENT client (general, certauthority?, basecerts)>  
<!ELEMENT server (general, certauthority?, basecerts, tempcerts?)>  
<!ELEMENT general EMPTY>  
<!ELEMENT certauthority EMPTY> 
<!ELEMENT basecerts (rsacert?,dsacert?,dhparams?)>  
<!ELEMENT tempcerts (rsacert*,dhparams*)>  
  
<!ATTLIST general  
        version (SSLv23|SSLv3|TLSv1) "SSLv23"  
        cipherlist CDATA #IMPLIED  
        context CDATA #IMPLIED  
        verifymode CDATA "none"  
        verifydepth CDATA "10"  
        randombytes CDATA #IMPLIED>  
  
<!ATTLIST certauthority 
        file CDATA #IMPLIED 
        path CDATA #IMPLIED>  
  
<!ELEMENT rsacert (public,private)>  
<!ATTLIST rsacert  
        keysize CDATA #REQUIRED>  
  
<!ELEMENT dsacert (public,private)>  
<!ATTLIST dsacert  
        keysize CDATA #REQUIRED>  
  
<!ELEMENT dhparams EMPTY>  
<!ATTLIST dhparams  
        keysize CDATA #REQUIRED  
        encoding CDATA #FIXED "PEM"  
        filename CDATA #REQUIRED>  
  
<!ELEMENT public EMPTY>  
<!ATTLIST public  
        encoding CDATA #FIXED "PEM"  
        filename CDATA #REQUIRED>  
  
<!ELEMENT private EMPTY>  
<!ATTLIST private  
        encoding CDATA #FIXED "PEM"  
        filename CDATA #REQUIRED>

=== BackupTheBerlios/openaqua-svn/trunk/odaba/unsupported/ODABAICEServer/etc/odaba/opiice/certs/client_sslconfig.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?> 
<!DOCTYPE SSLConfig SYSTEM "sslconfig.dtd"> 
<SSLConfig> 
    <client> 
        <general version="SSLv23" cipherlist="RC4-MD5" verifymode="peer" verifydepth="10" /> 
        <certauthority file="cacert.pem" />
        <basecerts> 
            <rsacert keysize="1024"> 
                <public  encoding="PEM" filename="c_rsa1024_pub.pem" /> 
                <private encoding="PEM" filename="c_rsa1024_priv.pem" /> 
            </rsacert> 
        </basecerts> 
    </client> 
</SSLConfig>
